server:
    port: "14515"
    token: token
nekoacm:
    host: localhost
    port: "14516"
    token: token
    timeout: 60
nacos:
    enable: true
    client:
        namespace-id: ""
        timeout-ms: 5000
        not-load-cache-at-start: true
        log-dir: /tmp/nacos/log
        cache-dir: /tmp/nacos/cache
        log-level: debug
    server:
        - ip-addr: localhost
          port: 8848
          scheme: http
          context-path: /nacos
    register:
        ip: 127.0.0.1
        port: 14516
        service-name: nekoacm-client
        weight: 10
        enable: true
        healthy: true
    config:
        group: DEFAULT_GROUP
